apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentic-api-ingress
  namespace: originhub-agentic
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - <your domain here>
      secretName: agentic-api-tls
  rules:
    - host: <your domain here>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agentic-api
                port:
                  number: 8004
